### ISSUE TITLE
add Metacity, Xfwm4 and Cinnamon

### ISSUE THREAD

**Issue by oberon2007** [manjaro/artwork-breath-gtk#2]
Should not be too much of a problem to make this more complete to make it available for more editions...

**Comment by Kirek** [comment]
No idea how to do that, I just used the script provided by https://github.com/dirruk1/gnome-breeze and the Breath colorschemes.

**Comment by oberon2007** [comment]
I will see if I can make some contribution here. Might be possible to use a different similar cinnamon theme as a basis and apply the necessary colors. For **xfwm4** we will basically just need to translate the assets to .xpm format and add a panelrc ... I can likely find some time for this during the week ... :)

**Comment by philmmanjaro** [comment]
Well, this is just for KDE. So not needed.
